# Generated by Django 5.0.4 on 2025-01-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendinggame'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
